name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install root deps
        run: npm ci
      - name: Install app deps
        working-directory: packages/cofhe-nextjs
        run: npm ci
      - name: Install Playwright Browsers (Chromium only)
        working-directory: packages/cofhe-nextjs
        run: npx playwright install chromium
      - name: Run E2E tests
        working-directory: packages/cofhe-nextjs
        env:
          CI: true
        run: npm run test:e2e

